[package]
name = "banque_postale_renamer"
version = "0.1.0"
authors = ["gsurrel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
anyhow = "1.0.34"
chrono = "0.4.19"
string_morph = "0.1.0"